import bcrypt from 'bcryptjs'

const data = {
  users: [
    {
      name: 'Administrator',
      email: 'admin@admin.com',
      password: bcrypt.hashSync('admin'),
      isAdmin: true,
    },
    {
      name: 'Example User',
      email: 'user@user.com',
      password: bcrypt.hashSync('user'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Mango',
      slug: 'mango-1',
      category: 'Fruits',
      image: '/images/orange.jpg',
      price: 30,
      brand: 'Fruits',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'Eng mazali mango faqat bizda!',
    },
    {
      name: 'Cherry',
      slug: 'cherry-1',
      category: 'Fruits',
      image: '/images/cherry.png',
      price: 24,
      brand: 'Fruits',
      rating: 4,
      numReviews: 5,
      countInStock: 200,
      description: 'Eng mazali giloslar faqat bizda!',
    },
    {
      name: 'Rukolli',
      slug: 'rukolli-1',
      category: 'Fruits',
      image: '/images/rukolli.jpg',
      price: 40,
      brand: 'Plants',
      rating: 3.5,
      numReviews: 7,
      countInStock: 200,
      description: "Nima uchun rukkola superfud mahsulot sanalar ekan? Birinchidan, unda temir va kalsiy ko’p bo’lib, suyak va qon-tomirlar faoliyatlarini yaxshilasa, ikkinchidan, hujayralarni qarishini sustlashtiradi, suv va tuz muvozanatini me’yorlashtiradi, quvvatlantirib asablarni tinchlantiradi. ",
    },
    {
      name: 'Mongold',
      slug: 'mongold-1',
      category: 'Fruits',
      image: '/images/mongold.jpg',
      price: 34,
      brand: 'Plants',
      rating: 3.5,
      numReviews: 7,
      countInStock: 200,
      description: "Nima uchun rukkola superfud mahsulot sanalar ekan? Birinchidan, unda temir va kalsiy ko’p bo’lib, suyak va qon-tomirlar faoliyatlarini yaxshilasa, ikkinchidan, hujayralarni qarishini sustlashtiradi, suv va tuz muvozanatini me’yorlashtiradi, quvvatlantirib asablarni tinchlantiradi. ",
    },
    {
      name: 'Gobilar zoti (Bichki)',
      slug: 'bichki-1',
      category: 'Animals',
      image: '/images/bichki.jpg',
      price: 400,
      brand: 'Plants',
      rating: 3.5,
      numReviews: 7,
      countInStock: 200,
      description: "Nima uchun rukkola superfud mahsulot sanalar ekan? Birinchidan, unda temir va kalsiy ko’p bo’lib, suyak va qon-tomirlar faoliyatlarini yaxshilasa, ikkinchidan, hujayralarni qarishini sustlashtiradi, suv va tuz muvozanatini me’yorlashtiradi, quvvatlantirib asablarni tinchlantiradi. ",
    },
  ],
}

export default data
